// This file would be generated by the FlutterFire CLI
// For demonstration purposes, I'm creating a placeholder
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // In a real app, these would be your actual Firebase configuration values
    return const FirebaseOptions(
      apiKey: 'AIzaSyBV6HNjx_eUFMh13zT4kmGzFr7g74aBjbY',
      appId: '1:872284472597:android:7eca7cc24e5bfba950d51c',
      messagingSenderId: '872284472597',
      projectId: 'wisedose-5b57a',
    );
  }
}

// To generate this file properly, run:
// flutterfire configure
